stripe/openapi

bin/update

This launches `git commit` with the `--editor` option which allows a
user to review changes before the entire operation goes through. It also
allows them to cancel the process by forcing their editor to exit with a
non-zero exit code (for example `:cq` in Vim).
This is useful in case some set of unexpected changes get pulled in from
pay-server and the operation needs to be aborted.

Commit files with `--editor`

---

README.md

Documents the various vendor extensions that the Stripe OpenAPI 2.0 spec
uses to represent non-standard things like expansions, polymorphic
resources, and fixtures.

Document Stripe vendor extensions

---

README.md

Now that we've got more than one version of the specification, it's not
super obvious what's happening in here anymore. Spell out what each file
is for in the README.

Update README with file descriptions

---

bin/update

Every time we release the openapi we will now publish a release. The releases will be tagged by `v{number}` where the number increments by one every time. See examples on [my test fork](https://github.com/ctrudeau-stripe/openapi/releases). We are adding this to have a canonical way to refer to an openapi version and let you compare two versions to know if one is later than the other.

Add logic to publish releases to github using v{number}

---

bin/update

When the user is not authenticated no token is returned. This will check to see the token is empty and throw an error to run auth instead. 
r? @richardm-stripe

Adding check to make sure token is returned

---

README.md
bin/update

r? @richardm-stripe 
Adds the ability to generate the changelog to add to the release. 
Test plan: 
- Added test mocks to repo
- Tested on fork https://github.com/ctrudeau-stripe/openapi/releases/

Add automatic changelog to releases

---

README.md

r? @yejia-stripe 
Updates docs URLs to no longer point to `/java`. This path doesn't exist anymore. This also doesn't need to be configured to a specific language.

Update docs URLs.

---

.github/workflows/publish.yml

Adds a workflow to update stripe-mock on openapi updates.
Uses my fork of stripe-mock for testing, I'll switch to the main repo after testing is done.

Automate stripe-mock update

---

.github/workflows/publish.yml

Requesting an actual review requires admin rights in the repo.

Move reviewer name into PR body

---

.github/workflows/publish.yml

Migrates the workflow to use GitHub Actions instead of a separate service account.
We also set the committer & author to the bot, instead of a human, so that it's clear what the commit came from. But perhaps we want the committer to be the `${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>` instead, since it was sorta initiated by them?
In the pull request body, I've included a link to the workflow, so we also know where the pull requests came from.
I've also made the bodies consistent, I'm happy to remove the `r? @username` from the second body?
I tested this here: https://github.com/qaisjp/stripe-mock/pull/1. We can see other GitHub Actions workflows being executed in this pull request.
It looks like this:
PTAL? @pakrym-stripe

Use GitHub Actions for creating pull requests

---

.github/workflows/ci.yml

r? @pakrym-stripe 
This is useful when something is wrong with the CI workflow and we want to test it.

Allow CI workflow to be kicked off manually.

---

bin/update

r? @pakrym-stripe 
Update the initial pull to also pull down tags, which are needed for `diff_spec`.

fix: Update bin/update to also pull tags from origin.

---

bin/update

Allows us greater flexibility in structuring the generator code.

Use yarn script to generate diff

---

bin/update

A follow-up to https://github.com/stripe/openapi/pull/104 to suppress extra logs.

Suppress yarn logs

---

README.md

This extension seems to have been used before to extend the
OpenAPI v2 format, but it is not used anymore as OpenAPI v3
offers a mechanism for polymorphic objects.

Remove unused x-polymorphicResources

---

.github/workflows/publish.yml

In a recent change the openapi spec was moved into subdirectory.

React to the openapi spec move in the stripe-mock repo

---

.github/workflows/publish.yml

The publish job is failing because it's running on every push. This PR updates the job to only run on commits to `master`.

Only run publish job on pushes to master

---

.github/workflows/publish.yml

Fixes a bug introduced in https://github.com/stripe/openapi/pull/125 that causes the publish workflow to be triggered before the new version is published, so generated PRs in the language repos don't reflect the latest tagged version.
This runs the publish workflow on both tag creation and pushes to master, cancelling any in-progress workflows.

Publish on tag creation and cancel in-progress publish jobs

---

.github/workflows/publish.yml

`github.ref` is different for tags - update the concurrency rule to cancel any run of the Publish workflow.

Cancel any in-progress Publish workflow

---

.github/workflows/publish.yml
actions/approve/action.yml
actions/enable-auto-merge/action.yml

gh cli behavior of resolving repo name from directory is funky and seems to use `upstream` sometimes instead of `origin`.

Use repo path instead of name in methods

---

actions/approve/action.yml

It created more problems than it solved as it requires extra permissions.

Remove extra logging

---

.github/workflows/publish.yml

Keep the publishing pipeline running while https://github.com/stripe/stripe-cli/pull/1124 is being resolved

Temporarily disable CLI publishing

---

.github/workflows/publish.yml

Codegen uses the latest release to determine the latest OpenAPI version. If it's triggered too early and the release is not done yet the new version is not picked up.

Trigger codegen only after the openapi release was created

---

.github/workflows/release.yml

Workflows don't trigger in response to actions performed by other workflows by default. (https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow) 
So when we release using the default TOKEN the https://github.com/stripe/openapi/blob/master/.github/workflows/publish.yml#L5 action is not triggered. Switching to an app token should solve that.

Publish release using openapi app

---

.github/workflows/publish.yml

To get the fix for https://github.com/peter-evans/create-pull-request/issues/2790 that's failing our builds at https://github.com/stripe/openapi/actions/runs/8085788161/job/22094093903

Update peter-evans/create-pull-request action to v6

---

openapi/fixtures3.json
openapi/fixtures3.yaml

A recent update to the fixture files upstream cleared the `scheduled_query_run` `file` object which is required for our SDK tests to complete successfully (by way of stripe-mock).  This is a manual update to unblock the tests before the next openapi release.  The content is identical to what will be in that release for this specific fixture.
- added the `file` object from git hustory to the `scheduled_query_run` object in `fixtures3.json` and `fixtures3.yaml`

Manually added scheduled_query_run file object

---

actions/notify-slack/action.yml

In order to better surface build failures before our users notice them, it's useful for the runner to get pinged when a build fails (rather than hoping they look at the channel)

mention SDKs runner on build failures

---

.github/workflows/publish.yml

Our [CI publish](https://github.com/stripe/openapi/actions/runs/12919429000/job/36029923560) started failing when stripe-cli updated the go version to 1.22. 
This PR updates our CI pipeline version of go to 1.22 in order to compile stripe-cli properly.

Updated go version to match update in stripe-cli

---

actions/stripe-mock/action.yml

From SDKs, we would like to use the stripe-mock action passing in our own spec and fixtures files. This addresses issues that can arise when the stripe-mock spec diverges from the one that's used for SDKs.

Allow for custom spec/fixture

---

actions/stripe-mock/action.yml

This adds an argument to this GH action to possible to provide an OpenAPI version as input and have the script pull the relevant SDK spec/fixtures for that api version.
This creates a much simpler flow for us when we have a version we know we need -- we do not need to pull the spec in the repos themselves. The codegen stripe-mock setup will still be a little more complicated, but it should make the language repos much simpler.
This adds 2 inputs to the script: `beta` and `openapi_version`.
I made the following calls, lmk if they make sense:
* You can only pass one of `openapi_version` or `spec_path`. I decided this since it requires the user to be very explicit about what they expect.
* If you provide both an `openapi_version` and `fixtures`, it will pull the spec version but use the …

Add option to pass a spec version for OpenAPI to test with and beta

---

actions/stripe-mock/action.yml

Tested with the openapi_version changes (https://github.com/stripe/openapi/pull/167/files), and the stripe-mock server didn't finish spinning up in time. This is a generous addition that should make sure we don't run into issues anytime soon.
(tested on https://github.com/stripe/stripe-dotnet/pull/3125/files, it used to fail due to not finding stripe-mock and now still failing but due to hitting the bad version of stripe-mock)

Add additional sleep time after docker run for stripe-mock action
